- hosts: all
  become: yes

  tasks:
  - name: install python packages
    pip:
      name:
        - cwltool==3.0.20200807132242
        - toil[cwl]==4.2.0
        - synapseclient==2.2.0
      executable: pip3
